apiVersion: v1
kind: Pod
metadata:
  name: pod_c-node1
  namespace: default
  labels:
    app: test-ping
    zone: group1
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["/bin/sh", "-c", "sleep infinity"]
    securityContext:
      capabilities:
        add: ["NET_RAW"]
  nodeSelector:
    kubernetes.io/hostname: minikube-m03
---
apiVersion: v1
kind: Pod
metadata:
  name: pod_d-node2
  namespace: default
  labels:
    app: test-ping
    zone: group2
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["/bin/sh", "-c", "sleep infinity"]
    securityContext:
      capabilities:
        add: ["NET_RAW"]
  nodeSelector:
    kubernetes.io/hostname: minikube-m02