apiVersion: v1
kind: Pod
metadata:
  name: alpine-on-m02
  labels:
    app: alpine
  namespace: default
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["/bin/sh", "-c", "sleep infinity"]
    securityContext:
      capabilities:
        add: ["NET_RAW"]
  nodeName: cluster-a-m02
