apiVersion: crd.projectcalico.org/v1
kind: IPPool
metadata:
  name: vxlan2-pool
spec:
  cidr: 10.300.0.0/16
  vxlanMode: Always
  natOutgoing: true
  nodeSelector: "kubernetes.io/hostname in {\"minikube-m05\", \"minikube-m06\"}"
  blockSize: 26