apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-node1
  namespace: default
  labels:
    app: test-ping
    zone: group1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-ping
      zone: group1
      pod-name: pod-node1
  template:
    metadata:
      labels:
        app: test-ping
        zone: group1
        pod-name: pod-node1
    spec:
      containers:
      - name: alpine
        image: alpine
        command: ["/bin/sh", "-c", "sleep infinity"]
        securityContext:
          capabilities:
            add: ["NET_RAW"]
      nodeSelector:
        kubernetes.io/hostname: cluster-c
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-node2
  namespace: default
  labels:
    app: test-ping
    zone: group2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-ping
      zone: group2
      pod-name: pod-node2
  template:
    metadata:
      labels:
        app: test-ping
        zone: group2
        pod-name: pod-node2
    spec:
      containers:
      - name: alpine
        image: alpine
        command: ["/bin/sh", "-c", "sleep infinity"]
        securityContext:
          capabilities:
            add: ["NET_RAW"]
      nodeSelector:
        kubernetes.io/hostname: cluster-c-m02
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-nodo3
  namespace: default
  annotations:
    fluxcd.io/last-applied: "2025-06-09T12:00:00Z"
  labels:
    app: test-ping
    zone: group1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-ping
      zone: group1
      pod-name: pod-nodo3
  template:
    metadata:
      labels:
        app: test-ping
        zone: group1
        pod-name: pod-nodo3
    spec:
      containers:
      - name: alpine
        image: alpine
        command: ["/bin/sh", "-c", "sleep infinity"]
        securityContext:
          capabilities:
            add: ["NET_RAW"]
      nodeSelector:
        kubernetes.io/hostname: cluster-c-m03
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-nodo4
  namespace: default
  labels:
    app: test-ping
    zone: group2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-ping
      zone: group2
      pod-name: pod-nodo4
  template:
    metadata:
      labels:
        app: test-ping
        zone: group2
        pod-name: pod-nodo4
    spec:
      containers:
      - name: alpine
        image: alpine
        command: ["/bin/sh", "-c", "sleep infinity"]
        securityContext:
          capabilities:
            add: ["NET_RAW"]
      nodeSelector:
        kubernetes.io/hostname: cluster-c-m04
